In [2]:
import numpy as np
import random

In [2]:
import time

In [252]:
a = list(range(0,10**7))
#sum(a

In [248]:
def FFT(A):
    x = np.log2(len(a))
    while x%1 != 0: 
        a.append(0)
        x = np.log2(len(a))
    
    n = len(A)
    if n==1:
        return A
    A0 = []
    A1 = []
    for i in range(0,n):
        A0.append(A[i]) if i%2 == 0 else A1.append(A[i])
    A0 = FFT(A0)
    A1 = FFT(A1)
    f = []
    i =0
    f.append(A0[0] + A1[0]) #np.exp(2*np.pi*complex("j")*i/n)*
    return f

In [254]:
start_time = time.time()
print(FFT(a))
print("--- %s seconds ---" % (time.time() - start_time))

KeyboardInterrupt: 

In [253]:
np.sum(a)

49999995000000

In [100]:
i = 0
n = 2
A0 = [0]
A1 = [4]
f = []

In [101]:
f.append(A0[int(i%(n/2))] + np.exp(2*np.pi*complex("j")*i/n)*A1[int(i%(n/2))])

In [102]:
f

[(4+0j)]

In [221]:
n = int(input())
two_in_power = 2
power = 1
while two_in_power <= n:
    two_in_power *= 2
    power += 1
print(power - 2, two_in_power // 2)


31
3 16


In [110]:
0 %5452

0

In [80]:
import numpy as np

a = np.array(range(0,6))
print(a)
cum_a = list(np.cumsum(a))
print(cum_a)

[0 1 2 3 4 5]
[0, 1, 3, 6, 10, 15]


In [102]:
m = 2
n = 4

In [103]:
#одновимірний випадок
np.sum(a[m:n])

5

In [104]:
cum_a[n-1]-cum_a[m-1]

5

In [78]:
def partial_sum(a,m,n):
    print("original\n",a)
    print("area\n",a[m:n])
    
    if m >= n:
        return "ERROR, wrong parameters: m >= n "
    cum_a = a.cumsum(axis=0)
    print("cumsum\n", cum_a)
    S0 = cum_a[n-1]
    S1 = -cum_a[m-1]
    print("np.sum = ",np.sum(a[m:n]) )
    if m == 0: S1 = 0
    S = S0 + S1
    return S0 + S1

In [81]:
partial_sum(a,m,n)

original
 [0 1 2 3 4 5]
area
 [0 1 2]
cumsum
 [ 0  1  3  6 10 15]
np.sum =  3


3

https://upload.wikimedia.org/wikipedia/commons/5/58/Summed_area_table.png

In [6]:
d = np.array([[1, 2, 3, 4,2],
              [3, 3, 5, 6,3],
              [7, 8, 9,10,4],
              [4, 5, 3,11,0]])
cum_d= d.cumsum(axis=0).cumsum(axis=1)

In [148]:
print(d)
print("   ")
print(cum_d)

[[ 1  2  3  4  2]
 [ 3  3  5  6  3]
 [ 7  8  9 10  4]
 [ 4  5  3 11  0]]
   
[[ 1  3  6 10 12]
 [ 4  9 17 27 32]
 [11 24 41 61 70]
 [15 33 53 84 93]]


In [212]:
print( d[1:3, 2:4])
print("sum =",np.sum(d[1:3, 2:4]))

[[ 5  6]
 [ 9 10]]
sum = 30


In [213]:
cum_d[2,3]  #I(D)

61

In [214]:
cum_d[0,1]  #I(A)

3

In [215]:
cum_d[0,3]  #I(B)

10

In [216]:
cum_d[2,1]  #I(C)

24

In [217]:
cum_d[2,3]  - cum_d[2,1] - cum_d[0,3]  + cum_d[0,1]

30

## I(D) - I(C) - I(B) + I(A)

In [7]:
d = np.array([[1, 2, 3, 4,2],
              [3, 3, 5, 6,3],
              [7, 8, 9,10,4],
              [4, 5, 3,11,0]])
cum_d= d.cumsum(axis=0).cumsum(axis=1)


In [4]:
m,n,i,j = 2,2,1,4 #1,3,2,4

In [5]:
print( d[m:n, i:j])
print("sum =",np.sum(d[m:n, i:j]))

[]
sum = 0


In [16]:
def summed_area_table(a,m,n,i,j):
    print("original\n",a)
    print("area\n",a[m:n, i:j])
    
    if m >= n or i >= j:
        return "ERROR, wrong parameters: m >= n or i >= j "
    
    cum_a = a.cumsum(axis=0).cumsum(axis=1)
    print("cumsum\n", cum_a)
    I_D = cum_a[n-1,j-1]
    I_C = -cum_a[n-1,i-1]
    I_B = -cum_a[m-1,j-1]
    I_A = cum_a[m-1,i-1]
    print("np.sum = ",np.sum(a[m:n, i:j]) )
    
    if i == 0 and m == 0: return I_D
    if m == 0: return I_D + I_C
    if i == 0: return I_D + I_B
    
    return I_D + I_C + I_B + I_A

In [17]:
summed_area_table(d, 0,2,0,3)

original
 [[ 1  2  3  4  2]
 [ 3  3  5  6  3]
 [ 7  8  9 10  4]
 [ 4  5  3 11  0]]
area
 [[1 2 3]
 [3 3 5]]
cumsum
 [[ 1  3  6 10 12]
 [ 4  9 17 27 32]
 [11 24 41 61 70]
 [15 33 53 84 93]]
np.sum =  17


17

In [3]:
m,n,i,j = 2,4,3,5 #1,3,2,4
print( d[m:n, i:j])
print("sum =",np.sum(d[m:n, i:j]))
cum_d[n-1,j-1]  - cum_d[n-1,i-1]  - cum_d[m-1,j-1] + cum_d[m-1,i-1]

NameError: name 'd' is not defined

In [7]:
a = np.random.rand(3,2,5)

In [86]:
g = np.array([[1, 2, 3, 4, 2, 3],
              [3, 3, 5, 6, 3, 5],
              [7, 8, 9, 5, 4, 7],
              [4, 5, 3, 1, 0, 1],
              [3, 7, 9, 8, 1, 4],
              [2, 5, 1, 7, 4, 6],
              [5, 1, 0, 1, 3, 7],
              [8, 4, 3, 2, 5, 6],
              [2, 3, 5, 6, 8, 1],
              [4, 6, 7, 1, 4, 9],
              [0, 2, 7, 8, 1, 5],
              [2, 3, 4, 6, 4, 2]],ndmin= 3).reshape(3,4,6)

In [87]:
g

array([[[1, 2, 3, 4, 2, 3],
        [3, 3, 5, 6, 3, 5],
        [7, 8, 9, 5, 4, 7],
        [4, 5, 3, 1, 0, 1]],

       [[3, 7, 9, 8, 1, 4],
        [2, 5, 1, 7, 4, 6],
        [5, 1, 0, 1, 3, 7],
        [8, 4, 3, 2, 5, 6]],

       [[2, 3, 5, 6, 8, 1],
        [4, 6, 7, 1, 4, 9],
        [0, 2, 7, 8, 1, 5],
        [2, 3, 4, 6, 4, 2]]])

In [10]:
g = g.reshape(3,4,6)

In [11]:
g.shape

(3, 4, 6)

In [12]:
g

array([[[1, 2, 3, 4, 2, 3],
        [3, 3, 5, 6, 3, 5],
        [7, 8, 9, 5, 4, 7],
        [4, 5, 3, 1, 0, 1]],

       [[3, 7, 9, 8, 1, 4],
        [2, 5, 1, 7, 4, 6],
        [5, 1, 0, 1, 3, 7],
        [8, 4, 3, 2, 5, 6]],

       [[2, 3, 5, 6, 8, 1],
        [4, 6, 7, 1, 4, 9],
        [0, 2, 7, 8, 1, 5],
        [2, 3, 4, 6, 4, 2]]])

In [14]:
cum_g = g.cumsum(axis=0).cumsum(axis=1).cumsum(axis=2)
cum_g

array([[[  1,   3,   6,  10,  12,  15],
        [  4,   9,  17,  27,  32,  40],
        [ 11,  24,  41,  56,  65,  80],
        [ 15,  33,  53,  69,  78,  94]],

       [[  4,  13,  25,  37,  40,  47],
        [  9,  26,  44,  69,  79,  97],
        [ 21,  47,  74, 105, 122, 154],
        [ 33,  68, 101, 135, 157, 196]],

       [[  6,  18,  35,  53,  64,  72],
        [ 15,  41,  71, 103, 125, 153],
        [ 27,  64, 110, 156, 186, 233],
        [ 41,  90, 146, 201, 240, 296]]])

In [55]:
l,k,m,n,i,j = 0,3,0,3,1,4                 #1,3,2,4,1,3
print( g[l:k,m:n, i:j])
print("sum =",np.sum(g[l:k,m:n, i:j]))

[[[2 3 4]
  [3 5 6]
  [8 9 5]]

 [[7 9 8]
  [5 1 7]
  [1 0 1]]

 [[3 5 6]
  [6 7 1]
  [2 7 8]]]
sum = 129


In [56]:
cum_g[k-1,n-1,j-1] - cum_g[k-1,n-1,i-1] - cum_g[k-1,m-1,j-1] - cum_g[l-1,n-1,j-1] + cum_g[l-1,m-1,j-1] + cum_g[l-1,n-1,i-1] + cum_g[k-1,m-1,i-1]- cum_g[l-1,m-1,i-1]

0

In [57]:
cum_g[k-1,n-1,j-1] - cum_g[k-1,n-1,i-1] - cum_g[k-1,m-1,j-1]  + cum_g[k-1,m-1,i-1]

-31

In [84]:
def summed_volume_table(a,l,k,m,n,i,j):
    print("original\n",a,'\n')
    print("volume\n",a[l:k,m:n, i:j],'\n')
    
    if l >=k or m >= n or i >= j:
        return "ERROR, wrong parameters: l >=k or m >= n or i >= j "
    
    cum_a = a.cumsum(axis=0).cumsum(axis=1).cumsum(axis=2)
    print("cumsum\n", cum_a,'\n')
    s0 =  cum_a[k-1,n-1,j-1]
    s1 = -cum_a[k-1,n-1,i-1]
    s2 = -cum_a[k-1,m-1,j-1]
    s3 = -cum_a[l-1,n-1,j-1]
    s4 =  cum_a[l-1,m-1,j-1]
    s5 =  cum_a[l-1,n-1,i-1] 
    s6 =  cum_a[k-1,m-1,i-1]
    s7 = -cum_a[l-1,m-1,i-1]
    print("np.sum =",np.sum(a[l:k,m:n, i:j]),'\n')
    
    if l == 0 and m == 0: s2 = s3 = s4 = s5 = s6 = s7 = 0
    if m == 0 and i == 0: s1 = s2 = s4 = s5 = s6 = s7 = 0  
    if l == 0 and i == 0: s1 = s3 = s4 = s4 = s6 = s7 = 0 
    if l == 0: s3 = s4 = s5 = s7 = 0
    if m == 0: s2 = s4 = s6 = s7 = 0
    if i == 0: s1 = s5 = s6 = s7 = 0
    s = s0 + s1 + s2 + s3 + s4 + s5 + s6 + s7
    return s

In [85]:
summed_volume_table(g,0,3, 0,3, 0,3)

original
 [[[1 2 3 4 2 3]
  [3 3 5 6 3 5]
  [7 8 9 5 4 7]
  [4 5 3 1 0 1]]

 [[3 7 9 8 1 4]
  [2 5 1 7 4 6]
  [5 1 0 1 3 7]
  [8 4 3 2 5 6]]

 [[2 3 5 6 8 1]
  [4 6 7 1 4 9]
  [0 2 7 8 1 5]
  [2 3 4 6 4 2]]] 

volume
 [[[1 2 3]
  [3 3 5]
  [7 8 9]]

 [[3 7 9]
  [2 5 1]
  [5 1 0]]

 [[2 3 5]
  [4 6 7]
  [0 2 7]]] 

cumsum
 [[[  1   3   6  10  12  15]
  [  4   9  17  27  32  40]
  [ 11  24  41  56  65  80]
  [ 15  33  53  69  78  94]]

 [[  4  13  25  37  40  47]
  [  9  26  44  69  79  97]
  [ 21  47  74 105 122 154]
  [ 33  68 101 135 157 196]]

 [[  6  18  35  53  64  72]
  [ 15  41  71 103 125 153]
  [ 27  64 110 156 186 233]
  [ 41  90 146 201 240 296]]] 

np.sum = 110 



110