In [57]:
import numpy as np
import matplotlib.pyplot as plt

In [58]:
a = np.random.randint(-20,20)
b = np.random.randint(-20,20)
r = np.random.randint(5,10)
a,b,r


(-16, 3, 6)

In [59]:
n = 50
data = np.array([[np.random.randint(-20,20),np.random.randint(-20,20)] for i in range(n)])
data= np.pad(data, (2,0), 'constant', constant_values=1)
data = data[2:]
data[:,1] = np.array([ data[i][2]**2 + data[i][3]**2 for i in range(len(data))])
test = data

In [60]:
in_round = []
out_round = []
epsilon = 3
for i in range(n):
    if (data[i][2] - a)**2 + (data[i][3] - b)**2 < r**2 :
        in_round.append(data[i])
    elif (data[i][2] - a)**2 + (data[i][3] - b)**2 > r**2 :
        out_round.append(data[i])
in_round = np.array(in_round)
out_round = np.array(out_round)

In [61]:
in_round = in_round*(-1)
in_round

array([[  -1, -178,   13,   -3],
       [  -1, -225,   15,    0],
       [  -1, -400,   20,    0],
       [  -1, -425,   20,   -5]])

In [62]:
#plt.plot(y_2,label='linear')
#from matplotlib.pyplot import figure
#figure(num=None, figsize=(8, 8), dpi=80, facecolor='w', edgecolor='k')
#plt.scatter(in_round[:,0],in_round[:,1]  )
#plt.scatter(out_round[:,0],out_round[:,1]  )
#plt.show()

In [63]:
alpha = np.zeros(4)
alpha

array([0., 0., 0., 0.])

In [64]:
s = np.vstack((in_round,out_round))

In [65]:
while ((s.dot(alpha)) <= 0).any():
    for i in range(n):
        if s[i].dot(alpha) <= 0:
            alpha += s[i]

In [66]:
alpha = alpha/alpha[1]
alpha

array([120.08279221,   1.        ,  26.01136364,  -7.20616883])

In [73]:
a_t = alpha[2]*(-0.5)
b_t = alpha[3]*(-0.5)
r_t = np.sqrt((a_t**2 + b_t**2 - alpha[0]))

In [74]:
print(a_t,b_t,r_t)
print(a,b,r)

-13.005681818181818 3.6030844155844157 7.8770035326779055
-16 3 6
