In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.random.randint(-20,20)
b = np.random.randint(-20,20)
r = np.random.randint(5,10)
a,b,r
a=b=r=1

In [3]:
#n = 50
n = 2

#data = np.array([[np.random.randint(-20,20),np.random.randint(-20,20)] for i in range(n)])
data = np.array([[1, 1], [1, -1]])
data= np.pad(data, (2,0), 'constant', constant_values=1)
data = data[2:]
data[:,1] = np.array([ data[i][2]**2 + data[i][3]**2 for i in range(len(data))])
test = data

In [4]:
in_round = []
out_round = []
epsilon = 1
for i in range(n):
    if (data[i][2] - a)**2 + (data[i][3] - b)**2 < r**2 :
        in_round.append(data[i])
        print(data[i])
    elif (data[i][2] - a)**2 + (data[i][3] - b)**2 > r**2  :
        out_round.append(data[i])
in_round = np.array(in_round)
out_round = np.array(out_round)

[1 2 1 1]


In [5]:
in_round = in_round*(-1)
in_round = np.vstack((in_round,np.array([0,1,0,0])))
in_round

array([[-1, -2, -1, -1],
       [ 0,  1,  0,  0]])

In [6]:
#plt.plot(y_2,label='linear')
#from matplotlib.pyplot import figure
#figure(num=None, figsize=(8, 8), dpi=80, facecolor='w', edgecolor='k')
#plt.scatter(in_round[:,0],in_round[:,1]  )
#plt.scatter(out_round[:,0],out_round[:,1]  )
#plt.show()

In [7]:
alpha = np.zeros(4)
alpha

array([0., 0., 0., 0.])

In [8]:
s = np.vstack((in_round,out_round))
s

array([[-1, -2, -1, -1],
       [ 0,  1,  0,  0],
       [ 1,  2,  1, -1]])

In [9]:
while ((s.dot(alpha)) <= 0).any():
    for i in range(n):
        if s[i].dot(alpha) <= 0:
            print(s[i], 'incorrect for', alpha, 'because', s[i].dot(alpha))
            alpha += s[i]
            print('after correction', alpha)

[-1 -2 -1 -1] incorrect for [0. 0. 0. 0.] because 0.0
after correction [-1. -2. -1. -1.]
[0 1 0 0] incorrect for [-1. -2. -1. -1.] because -2.0
after correction [-1. -1. -1. -1.]
[0 1 0 0] incorrect for [-1. -1. -1. -1.] because -1.0
after correction [-1.  0. -1. -1.]
[0 1 0 0] incorrect for [-1.  0. -1. -1.] because 0.0
after correction [-1.  1. -1. -1.]


In [10]:
while ((s.dot(alpha)) <= 0).any():
    for i in range(len(s)):
        if s[i].dot(alpha) <= 0:
            alpha += s[i]

In [11]:
alpha = alpha/alpha[1]
alpha

array([-1.,  1., -1., -1.])

In [12]:
a_t = alpha[2]*(-0.5)
b_t = alpha[3]*(-0.5)
r_t = np.sqrt((a_t**2 + b_t**2 - alpha[0]))

In [13]:
print(a_t,b_t,r_t)
print(a,b,r)

0.5 0.5 1.224744871391589
1 1 1


In [ ]:
def parameters():
    a = np.random.randint(-20,20)
    b = np.random.randint(-20,20)
    r = np.random.randint(5,10)
    return a,b,r